'use client';

import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import { defaultKeygenSpec, SERVER_KEYGEN_SPECS, type ServerKeygenType } from '@/lib/ra-form';
import { RaFormSection, SettingSwitch } from './RaFormSection';
import type { RaSectionProps } from './types';

export function KeygenSection({ values, update }: RaSectionProps) {
  const { serverKeygen } = values;
  const setKeygen = (patch: Partial<typeof serverKeygen>) => update({ serverKeygen: { ...serverKeygen, ...patch } });

  return (
    <RaFormSection
      id="keygen"
      title="Server-side key generation"
      description="Let constrained devices request a key pair generated by the platform (EST serverkeygen)."
    >
      <SettingSwitch
        id="enableKeyGeneration"
        label="Enable server-side key generation"
        description="The private key is generated on the server and returned to the device with its certificate."
        checked={serverKeygen.enabled}
        onCheckedChange={enabled => setKeygen({ enabled })}
      />
      {serverKeygen.enabled && (
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="space-y-1.5">
            <Label id="serverKeygenType-label">Algorithm</Label>
            <ToggleGroup
              type="single"
              variant="outline"
              aria-labelledby="serverKeygenType-label"
              value={serverKeygen.type}
              onValueChange={(type: ServerKeygenType | '') => {
                if (type) setKeygen({ type, spec: defaultKeygenSpec(type) });
              }}
            >
              <ToggleGroupItem value="RSA" className="px-4">RSA</ToggleGroupItem>
              <ToggleGroupItem value="ECDSA" className="px-4">ECDSA</ToggleGroupItem>
            </ToggleGroup>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="serverKeygenSpec">{serverKeygen.type === 'RSA' ? 'Key size' : 'Curve'}</Label>
            <Select value={serverKeygen.spec} onValueChange={spec => setKeygen({ spec })}>
              <SelectTrigger id="serverKeygenSpec"><SelectValue /></SelectTrigger>
              <SelectContent>
                {SERVER_KEYGEN_SPECS[serverKeygen.type].map(spec => (
                  <SelectItem key={spec.value} value={spec.value}>{spec.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </div>
      )}
    </RaFormSection>
  );
}
