name: "Release Workflow"

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: release version when building docker containers (example; 2.0.0)

run-name: >-
  ${{ format('Release {0}', github.event.inputs.release_version) }}
        
jobs:
  build_aws_connector_docker_image:
    name: Release docker images
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Login to Github Registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    # Enable ARM64 emulation for multi-platform Docker builds on AMD64 runners.
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Build Docker image
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        build-args: |
          SHA1VER=${{ env.SHA1VER }}
          VERSION=${{ github.event.inputs.release_version }}
        tags: |
          ghcr.io/lamassuiot/lamassu-ui:${{ github.event.inputs.release_version }}
          ghcr.io/lamassuiot/lamassu-ui:latest
        push: true
      
    - name: Create tag
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ github.event.inputs.release_version }}',
            sha: context.sha
          })

    - name: Generate Release Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@c9dc8369bccbc41e0ac887f8fd674f5925d315f7 # v5
      with:
        configuration: '.github/changelog-configuration.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_version }}
        release_name: Release v${{ github.event.inputs.release_version }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false

    - name: Build project
      run: npm ci && npm run build

    - name: Zip out folder
      run: |
        if [ -d "out" ]; then
          zip -r release.zip out
        else
          echo "No out folder found to zip."
        fi

    - name: Upload Release Asset
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: success()
      with:
        tag_name: ${{ github.event.inputs.release_version }}
        files: release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}